spring:
  datasource:
    url: jdbc:mysql://192.168.40.133:3360/permission?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: 123456
    username: root